loja/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('',include('produto.urls')),
    path('perfil/',include('perfil.urls')),
    path('pedido',include('pedido.urls')),
    path('admin/', admin.site.urls),
  
    ] +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

pedido/urls.py
from django.urls import path
from . import views


app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'


urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views


app_name = 'produto'


urlpatterns = [
    path('',views.ListaProdutos.as_view(),name="lista"),
    path('<slug>',views.DetalheProduto.as_view(),name="detalhe"),
    path('adicionaraocarrinho/',views.AdicionarAoCarrinho.as_view(),name="adicionaraocarrinho"),
    path('removerdocarrinho/',views.RemoverDoCarrinho.as_view(),name="removerdocarrinho"),
    path('carrinho/',views.Carrinho.as_view(),name="carrinho"),
    path('finalizar/',views.Carrinho.as_view(),name="finalizar"),
    path('resumodacompra/',views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('busca/', views.Busca.as_view(), name="busca"),
]

pedido/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User


class Pedido(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default="C",
        max_length=1,
        choices=(
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
        )
    )

    def __str__(self):
        return f'Pedido N. {self.pk}'


class ItemPedido(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

pedido/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views import View
# from django.http import HttpResponse
from django.contrib import messages
from django.http import HttpResponse
from produto.models import Variacao
from .models import Pedido, ItemPedido
from django.urls import reverse
from utils import utils

class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(usuario=self.request.user)
        return qs



class Pagar(DispatchLoginRequiredMixin,DetailView):
    template_name = 'pedido/pagamento.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'

class FecharPedido(View):
    def get(self,*args, **kwargs):
        return HttpResponse('FecharPedido')


class SalvarPedido(View):
    template_name = 'pedido/pagamento.html'
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            usuario=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhes.html'
    pk_url_kwarg = 'pk'

templates/parciais/_carrinho.html
{%load static%}
{% load omfilters %}
<li class="list-group-item py-3">
    {%for linha in carrinho.values %}
    <div class="row g-3 mt-2">
      <div class="col-4 col-md-3 col-lg-2">
        <a href="">
          <img src="{%get_media_prefix%}{{linha.imagem}}" class="img-thumbnail">
        </a>
      </div>
      <div class="col-8 col-md-9 col-lg-7 col-xl-8 text-left align-self-center">
        <h4>
         <b><a href="{%url 'produto:detalhe' linha.slug%}" class="text-decoration-none text-dark ">
          {{linha.produto_nome}}
         </a></b>
         <h5>
          {{linha.variacao_nome}}
         </h5>
        </h4>
      </div>
       <div class="col-6 offset-6 col-sm-6 offset-sm-6 col-md-4 offset-md-8 col-lg-3 offset-lg-0 col-xl-2 align-self-center mt-3 ">
        <div class="input-group">
          <button class="btn btn-outline-dark btn-sm" type="button">
            <i class="bi-caret-down" style="font-size: 16px; line-height: 24px;"></i>
          </button>
          <input type="text" class="form-control text-center border-dark" value="{{linha.quantidade}}" placeholder="Recipient's username" aria-label="Recipient's username with two button addons">
          
          <button class="btn btn-outline-dark btn-sm" type="button">
            <i class="bi-caret-up" style="font-size: 16px; line-height: 24px;"></i>
          </button>

          <button class="btn btn-outline-dark border-dark btn-sm"  type="button">
            <a style="color: rgb(255, 0, 0);" href="{%url 'produto:removerdocarrinho'%}?vid={{linha.variacao_id}}">
            <i class="bi-trash" style="font-size: 16px; line-height: 24px;"></i>
            </a>
          </button>
        </div>
          <div class="text-end mt-2">
            {%if linha.preco_unitario_promocional%}
            
            <small class="text-dark">Valor unitário: {{linha.preco_unitario_promocional|formata_preco}}</small>
            {%else%}
           
            <small class="text-dark">Valor unitário: {{linha.preco_unitario|formata_preco}}</small>

            {%endif%}

            {%if linha.preco_quantitativo_promocional%}
            
            <small class="text-dark"><br>Total: {{linha.preco_quantitativo_promocional|formata_preco}}</small>
            {%else%}
           
            <small class="text-dark"><br>Total: {{linha.preco_quantitativo|formata_preco}}</small>

            {%endif%}
          </div>
       </div>
    </div>
    {%endfor%}
    
  </li>

templates/parciais/_footer.html
{% load static %}
<footer>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <ul class="social-icon mb-4">
            <li>
              <a href="" target="_blank">
                <i class="bi-facebook"></i>
              </a>
            </li>
    
            <li>
              <a href="" target="_blank">
                <i class="bi-twitter"></i>
              </a>
            </li>
    
            <li>
              <a href="" target="_blank">
                <i class="bi-pinterest"></i>
              </a>
            </li>
    
            <li>
              <a href="" target="_blank">
                <i class="bi-instagram"></i>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-md-6">
          <div class="newsletter">
            <span class="news-icon">
              <i class="bi bi-newspaper"></i>
            </span>
            <h4>Newslatter</h4>
            <p>Samia dostialkdolsadfjfpoijfdhssfdoipjfd
              gdsgdgddgssgd
              sggsdgsdgsdgsd
              sggsdgsd
            </p>
            <form>
              <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="button-addon2">
                <button class="btn btn-outline-secondary" type="button" id="button-addon2">Button</button>
              </div>
            </form>
          </div>
          <div class="footer-nav">
            <ul>
              <li><a href="">Página inicial</a></li>
              <li><a href="">Sobre nós</a></li>
              <li><a href="">Política de privacidade</a></li>
              <li><a href="">Termos e condições</a></li>
              <li><a href="">Atendimento</a></li>
              <li><a href="">Nossa feira </a></li>
            </ul>
          </div>
        </div>
        
        <div class="col-md-3">
          <div class="payment-icon-footer">
            <img src="{% static 'image/wirecard-selos-pequeno-horizontal.png'%}" alt="" class="img-fluid">
          </div>
        </div>
      </div>
    </div>
      </footer>

      <script src="{% static 'node_modules/jquery/dist/jquery.min.js'%}"></script>
<script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js'%}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

templates/parciais/_head.html
{% load static %}
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link rel="stylesheet" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css'%}">
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <link rel="stylesheet" href="{% static 'css/resposive.css'%}">
  <link rel="stylesheet" href="{% static 'node_modules/animate.css/animate.min.css'%}">
  <link rel="stylesheet" href="{% static 'css/style_index.css'%}">
  <link rel="stylesheet" href="{% static 'css/estilo_detalhes_Produto.css'%}">
  
</head>
  

  

templates/parciais/_header-nav.html
{% load static %}
{%load omfilters%}
<header>
    <div class="topbar">
     <div class="container-xxl">
       <div class="row">
         <div class="col-md-5">
           <div class="top-left">
             <span class="badge bg-info text-dark">Novo</span>
             <a href="">Promoções imperdíveis! Clique aqui</a>
           </div>
         </div>
         <div class="col-md-7 ">
           <div class="top-right">
             <ul class="rightElement">
               <li>
                 <a href="">
                   <i class="bi bi-geo-alt-fill"> Locais de venda</i>
                 </a>
               </li>
 
               <li>
                 <a href="">
                   <i class="bi bi-file-text"> Rastreie aqui</i>
                 </a>
               </li>
               
             </ul> 
 
             <div class="myAccount-nav">
               <span><a href=""><i class="bi bi-gear"> Sua conta</i><i class="bi bi-caret-down mx-1"></i></a></span>
               <ul class="myAccount-dropdown">
                {% if request.user.is_authenticated %}
                 <li>
                   <a href="{% url 'pedido:lista'%}">Pedidos</a>
                 </li>
 
                 <li>
                   <a href="{% url 'perfil:criar'%}">Atualizar</a>
                 </li>
 
                 <li>
                   <a href="{% url 'perfil:logout'%}">Sair</a>
                 </li>
                 {% else %}
                 <li>
                  <a href="{% url 'perfil:criar'%}">Cadastre-se</a>
                </li>
                {%endif%}

               </ul>
             </div>
           </div>
         </div>
       </div>
     </div>
    </div>
 
    <div class="header-middle">
     <div class="container-xxl">
       <div class="row">
         <div class="col-md-3 col-lg-3 position-relative">
           <div class="logo">
           Poti<span>Eco</span>
           </div>
 
           <div id="poti"><i class="bi bi-text-paragraph"><p id="dica">menu</p></i></div>
         </div>
 
         <div class="col-md-12 col-lg-5 search-order">
           <div class="header-search">
             <form method="GET" action="{% url 'produto:busca'%}">
                 <div class="input-group mb-3">
                   <input name="termo" value="{{request.GET.termo}}" type="search" class="form-control" placeholder="Pesquise produtos aqui">
                   <div class="input-group-append">
                     <button class="btn btn-secondary btn-bg" type="submit">
                       <i class="bi bi-search"></i>
                     </button>
                   </div>
               </div>
             </form>
           </div>
         </div>
 
         <div class="col-md-9 col-lg-4">
           <div class="middle-header-right">
 
             <div class="sign-register">
               <i class="bi bi-person"></i>
               {% if request.user.is_authenticated %}
               <p><a href="{% url 'perfil:criar'%}">Bem vindo,</a><br><a href="{% url 'perfil:criar'%}"> <span class="">{{user}}</span></a></p>
               
               {%else%}
               <p><a href="{% url 'perfil:criar'%}">Cadastre-se</a><br> ou <a href="{% url 'perfil:criar'%}">Entre</a></p>
               
               {%endif%}
               
             </div>
 
             <div class="wishlist-widget">
               <a href="">
                 <i class="bi bi-heart"></i>
               </a>
             </div>
 
             <div class="my-cart-widget">
               <button class="btn position-relative">
                 <a href="{% url 'produto:carrinho'%}"><i class="bi bi-bag"></i></a>
                 {% if request.session.carrinho %}
                 <span class="position-absolute translate-middle badge rounded-pill bg-success mt-4 ms-0">{{request.session.carrinho | cart_total_qtd}}</span>
                 {%else%}
                 <span class="position-absolute translate-middle badge rounded-pill bg-success mt-4 ms-0" style="font-size: 10px;">vazio</span>
                 {% endif %}
               </button>
               <span>Carrinho</span>
               
               <div class="my-cart-list">
                 <ul>
                   <li>
                     <a href="{% url 'produto:carrinho'%}">
                       <h6>Clique para ver o carrinho:</h6>
                       {% if request.session.carrinho %}
                       <div class="cart-prod-rate">{{request.session.carrinho | cart_total_qtd}} itens adicionados</div>
                       {% endif %}
                     </a>
                   </li>
 
                   
                 </ul>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
    </div>
 
    <nav>
     <div class="container-xxl">
       <div class="nav-collapse">
         <div id="closeBtn">X</div>
         <ul class="custom-nav">
           <li class="cst-nav-item">
             <a href="{% url 'produto:lista'%}" class="cst-nav-link">Página inicial</a>
           </li>
           <li class="cst-nav-item cst-dropdown">
             <a href="" class="cst-nav-link">Nossos produtos<i class="bi bi-chevron-down"></i></a>
             <ul class="cst-dropdown-menu">
               <li>
                 <a href="" class="cst-dropdown-link">Cereais, pães e tubérculos</a>
               </li>
 
               <li>
                 <a href="" class="cst-dropdown-link">Hortaliças</a>
               </li>
 
               <li>
                 <a href="" class="cst-dropdown-link">Carnes</a>
               </li>
 
               <li>
                 <a href="" class="cst-dropdown-link">Frutas</a>
               </li>
 
               <li>
                 <a href="" class="cst-dropdown-link">Produtos derivados</a>
               </li>
             </ul>
           </li>
           <li class="cst-nav-item">
             <a href="" class="cst-nav-link">Ofertas</a>
           </li>
           <li class="cst-nav-item">
             <a href="" class="cst-nav-link">Sobre nós</a>
           </li>
           <li class="cst-nav-item">
             <a href="" class="cst-nav-link">Contato</a>
           </li>
 
   
         </ul>
        
       </div>
     </div>
    </nav>
 
   </header>

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}

templates/parciais/_pedido.html
{% load static %}
{% load omfilters %}

<div class="row">
    <div class="col">
        <h3>{{ pedido }}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{ pedido.id }}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{ pedido.total|formata_preco }}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{ pedido.qtd_total }}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{ pedido.get_status_display }}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for linha in pedido.itempedido_set.all %}
                <tr>
                    <td class="d-none d-lg-block">
                        <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
                    </td>
                    <td>{{ linha.produto }}</td>
                    <td>{{ linha.variacao }}</td>
                    <td>{{ linha.quantidade }}</td>
                    <td>
                        {% if linha.preco_promocional %}
                        {{ linha.preco_promocional|formata_preco }}
                        {% else %}
                        {{ linha.preco|formata_preco }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>